upgrade pip to fix dependency installation issues
The following error was introduced by updates in the dependency tree:
ValueError: ('Expected version spec in', 'tornado ~=4.5', 'at', ' ~=4.5')
Newer version of pip is required to resolve all dependencies
in requirements.txt.

Change-type: patch
Signed-off-by: Csaba Kiraly <csaba.kiraly@gmail.com>